# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170625_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='imagem',
        ),
    ]
